analyzer: word
binary: false
decode_error: strict
dtype: <class 'numpy.float64'>
encoding: utf-8
input: content
lowercase: true
max_df: 1.0
max_features: 25000
min_df: 1
model:
  bootstrap: true
  ccp_alpha: 0.0
  class_weight: balanced
  criterion: gini
  max_depth: null
  max_features: auto
  max_leaf_nodes: null
  max_samples: null
  min_impurity_decrease: 0.0
  min_impurity_split: null
  min_samples_leaf: 1
  min_samples_split: 2
  min_weight_fraction_leaf: 0.0
  n_estimators: 100
  n_jobs: null
  oob_score: false
  random_state: 13
  verbose: 0
  warm_start: false
model_class: RandomForestClassifier
ngram_range: (1, 1)
norm: l2
preprocessor: null
smooth_idf: true
stop_words: null
strip_accents: null
sublinear_tf: false
token_pattern: (?u)\b\w\w+\b
tokenizer: null
use_idf: true
vocabulary: null
